export type BangalorePincodeEntry = {
  pincode: string;
  areas: string[];
};

export const bangalorePincodeData: BangalorePincodeEntry[] = [
  { pincode: '560001', areas: ['M G Road', 'Bangalore GPO', 'Vidhana Soudha', 'Raj Bhavan'] },
  { pincode: '560002', areas: ['Bangalore City H.O.', 'Avenue Road', 'Kalasipalya'] },
  { pincode: '560003', areas: ['Malleswaram', 'Seshadripuram', 'Sadashivanagar'] },
  { pincode: '560004', areas: ['Basavanagudi', 'Gandhi Bazaar', 'Bull Temple Road'] },
  { pincode: '560005', areas: ['Fraser Town', 'Cox Town', 'Benson Town'] },
  { pincode: '560006', areas: ['High Grounds', 'Vasanth Nagar', 'Sampangi Rama Nagar'] },
  { pincode: '560007', areas: ['Ulsoor', 'Halasuru', 'Cambridge Layout'] },
  { pincode: '560008', areas: ['Shivajinagar', 'Jogupalya', 'Pulikeshi Nagar'] },
  { pincode: '560009', areas: ['Chickpet', 'Cottonpet', 'Bangalore Fort'] },
  { pincode: '560010', areas: ['Rajajinagar', 'Basaveshwaranagar', 'Mahalakshmi Layout'] },
  { pincode: '560011', areas: ['Jayanagar', 'Jayanagar East', 'Srinagar'] },
  { pincode: '560012', areas: ['Science Institute', 'C V Raman Nagar', 'Kasturinagar'] },
  { pincode: '560013', areas: ['Yeshwanthpur', 'M S Ramaiah Nagar', 'Peenya'] },
  { pincode: '560014', areas: ['Jalahalli', 'Bagalakunte', 'Nagasandra'] },
  { pincode: '560015', areas: ['Bangalore Air Force', 'Halasuru', 'Murgesh Pallya'] },
  { pincode: '560016', areas: ['Whitefield', 'Mahadevapura', 'Nallurhalli'] },
  { pincode: '560017', areas: ['Domlur', 'Old Airport Road', 'Kodihalli'] },
  { pincode: '560018', areas: ['Adugodi', 'Wilson Garden', 'Lalbagh Road'] },
  { pincode: '560019', areas: ['Girinagar', 'BSK 2nd Stage', 'Hanumanthanagar'] },
  { pincode: '560020', areas: ['K G Road', 'Cubbonpet', 'Shankarapuram'] },
  { pincode: '560021', areas: ['Seshadripuram', 'Anand Rao Circle', 'Race Course Road'] },
  { pincode: '560022', areas: ['M S Ramaiah Nagar', 'Mathikere', 'Bangalore University'] },
  { pincode: '560023', areas: ['Deepanjalinagar', 'Mysore Road', 'Nayandahalli'] },
  { pincode: '560024', areas: ['RT Nagar', 'Ganganagar', 'Sultanpalya'] },
  { pincode: '560025', areas: ['Richmond Town', 'Langford Town', 'Ashok Nagar'] },
  { pincode: '560026', areas: ['Vijayanagar', 'Hampinagar', 'RPC Layout'] },
  { pincode: '560027', areas: ['J P Nagar', 'Yelachenahalli', 'Puttenahalli'] },
  { pincode: '560029', areas: ['B T M Layout', 'Tavarekere', 'Madiwala'] },
  { pincode: '560030', areas: ['Hosur Road', 'Bommanahalli', 'Harlur'] },
  { pincode: '560031', areas: ['K R Puram', 'Ramamurthy Nagar', 'Horamavu'] },
  { pincode: '560032', areas: ['Bannerghatta Road', 'Anekal Road', 'Doddakallasandra'] },
  { pincode: '560033', areas: ['Marathahalli', 'Kundalahalli', 'Doddanekundi'] },
  { pincode: '560034', areas: ['Koramangala', 'Madiwala', 'St. Johns Road'] },
  { pincode: '560035', areas: ['HSR Layout', 'Agara', 'Sector 1-7'] },
  { pincode: '560036', areas: ['Electronic City', 'Hosa Road', 'Konappana Agrahara'] },
  { pincode: '560037', areas: ['Bellandur', 'Kaikondrahalli', 'Sarjapur Road'] },
  { pincode: '560038', areas: ['Indiranagar', 'CMH Road', 'HAL 2nd Stage'] },
  { pincode: '560039', areas: ['Kengeri', 'Mysore Road', 'Ullal'] },
  { pincode: '560040', areas: ['Vijayanagar', 'Nagarbhavi', 'Chandra Layout'] },
  { pincode: '560041', areas: ['J P Nagar', 'Puttenahalli', 'Bilekahalli'] },
  { pincode: '560042', areas: ['BTM Layout', 'Tavarekere', 'Jayanagar 9th Block'] },
  { pincode: '560043', areas: ['Kalyan Nagar', 'Hennur', 'Banaswadi'] },
  { pincode: '560045', areas: ['Kalyan Nagar', 'HBR Layout', 'Cooke Town'] },
  { pincode: '560046', areas: ['Frazer Town', 'Cox Town', 'Benson Town'] },
  { pincode: '560047', areas: ['Jayanagar', 'Tilak Nagar', 'Banashankari'] },
  { pincode: '560048', areas: ['KR Puram', 'Mahadevapura', 'Hoodi'] },
  { pincode: '560049', areas: ['KR Puram', 'Old Madras Road', 'Bhattarahalli'] },
  { pincode: '560050', areas: ['Banashankari', 'Padmanabhanagar', 'Kathriguppe'] },
  { pincode: '560051', areas: ['Jayanagar', 'Shanthi Nagar', 'Langford Town'] },
  { pincode: '560052', areas: ['Richmond Town', 'Hosur Road', 'Shanthinagar'] },
  { pincode: '560053', areas: ['Chickpet', 'K R Market', 'Balepet'] },
  { pincode: '560054', areas: ['Sanjay Nagar', 'RMV Extension', 'Mathikere'] },
  { pincode: '560055', areas: ['Airport', 'Devanahalli', 'KIAL'] },
  { pincode: '560056', areas: ['RR Nagar', 'Kengeri Satellite Town', 'Mysore Road'] },
  { pincode: '560057', areas: ['Nagarbhavi', 'Chandra Layout', 'Vijayanagar'] },
  { pincode: '560058', areas: ['Peenya', 'T Dasarahalli', 'Hegganahalli'] },
  { pincode: '560059', areas: ['Kengeri', 'NICE Road', 'Bidadi Road'] },
  { pincode: '560060', areas: ['Kumbalgodu', 'Mysore Road', 'Rajarajeshwari Nagar'] },
  { pincode: '560061', areas: ['Anjanapura', 'JP Nagar 9th Phase', 'Konanakunte'] },
  { pincode: '560062', areas: ['Kanakapura Road', 'Vajarahalli', 'Thalaghattapura'] },
  { pincode: '560063', areas: ['Yelahanka', 'Kogilu', 'Sahakar Nagar'] },
  { pincode: '560064', areas: ['Yelahanka New Town', 'Attur', 'Doddaballapur Road'] },
  { pincode: '560065', areas: ['Hebbal', 'Sahakar Nagar', 'Kodigehalli'] },
  { pincode: '560066', areas: ['Whitefield', 'Hope Farm', 'ITPL'] },
  { pincode: '560067', areas: ['Marathahalli', 'Brookefield', 'AECS Layout'] },
  { pincode: '560068', areas: ['Bommanahalli', 'HSR Layout', 'Somasundarapalya'] },
  { pincode: '560069', areas: ['Bannerghatta Road', 'Bilekahalli', 'Arekere'] },
  { pincode: '560070', areas: ['Jayanagar', 'South End Circle', 'Gandhi Bazaar'] },
  { pincode: '560071', areas: ['Domlur', 'Kodihalli', 'HAL 2nd Stage'] },
  { pincode: '560072', areas: ['Nagarbhavi', 'Chandra Layout', 'Moodalapalya'] },
  { pincode: '560073', areas: ['Hesaraghatta', 'T Dasarahalli', 'Bagalagunte'] },
  { pincode: '560074', areas: ['Kengeri', 'Mylasandra', 'Uttarahalli'] },
  { pincode: '560075', areas: ['HAL', 'Old Airport Road', 'Murgesh Pallya'] },
  { pincode: '560076', areas: ['Bilekahalli', 'Adugodi', 'Bannerghatta Road'] },
  { pincode: '560077', areas: ['Hennur', 'Banaswadi', 'Kalyan Nagar'] },
  { pincode: '560078', areas: ['JP Nagar', 'Puttenahalli', 'RBI Layout'] },
  { pincode: '560079', areas: ['Rajajinagar', 'Mahalakshmi Layout', 'Nandini Layout'] }
];
